#!/usr/bin/env node
/*
 * Publish tools/rst2md/_terms.md as docs/glossary/terms.md.
 *
 * The upstream `terms.rst` was a placeholder page that listed every
 * `:ref:` cross-reference target used across the protocol docs. Each
 * entry is an anchor (e.g. `(term-coinbase-block-height)=`) followed
 * by a one-line description.
 *
 * For the migrated site we publish those anchors as a real page at
 * `/glossary/terms`, with each entry rendered as a heading + HTML
 * anchor pair. `scripts/postprocess-rst.mjs` then reads this page to
 * build a name → URL map for the autocrossref-resolve pass.
 *
 * One-shot. After Phase 1 closes and inline anchors replace this
 * registry, the script can be archived along with convert-rst.mjs and
 * the postprocess driver.
 */

import {existsSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const repo = dirname(dirname(fileURLToPath(import.meta.url)));
const SRC = join(repo, 'tools/rst2md/_terms.md');
const DST = join(repo, 'docs/glossary/terms.md');

if (!existsSync(SRC)) {
  console.error(`source missing: ${SRC}`);
  process.exit(1);
}

const raw = readFileSync(SRC, 'utf8');

// Block-split on blank lines, then pair each (anchor)= block with
// the description that follows it.
const blocks = raw.split(/\n\s*\n/);
const entries = [];
for (let i = 0; i < blocks.length - 1; i++) {
  const trimmed = blocks[i].trim();
  const m = trimmed.match(/^\(([a-z][a-z0-9_-]*)\)=$/);
  if (m) {
    entries.push({anchor: m[1], desc: blocks[i + 1].trim()});
    i++; // consume the description block
  }
}

const header = `---
id: terms
title: Terms
description: Cross-reference targets used throughout the ReddCoin protocol documentation.
---

# Terms

Cross-reference anchors used throughout the protocol documentation.
Each entry below is a target for \`:ref:\`-style links from the
protocol pages.

This page is generated by \`scripts/publish-terms.mjs\` from
\`tools/rst2md/_terms.md\` (originally \`terms.rst\` in the upstream
\`developer.reddcoin.com\` repo). Inline anchors will eventually
replace this registry — see the upstream note in the source — but
until then this is the canonical landing for \`term-*\` cross
references.

`;

const sections = entries
  .map(e => `## \`${e.anchor}\` {#${e.anchor}}\n\n${e.desc}`)
  .join('\n\n');

writeFileSync(DST, header + sections + '\n');
console.log(`wrote ${DST} with ${entries.length} entries`);
